redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development: # *redis
  adapter: async
  # url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: ENV['REDISTOGO_URL']
  channel_prefix: chess-adventure-backend_production
