redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development: *redis
  # adapter: async
  # url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:911a53b9cc0b8b5d429ff58f802f4347@scat.redistogo.com:11504/
  channel_prefix: chess-adventure-backend_production
