development:
  adapter: async
  # url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: async # redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: chess-adventure-backend_production
